Desktop/EscolaDotNet/AplicativoWeb/Models/Curso.cs
//Conjunto de Classes
namespace AplicativoWeb.Models;
public class Curso{    
    public int Id { get; set; }
    public string? TituloMarketing { get; set; }
    public string? TituloInterno { get; set; }
    public string? Descricao { get; set; }
}

Desktop/EscolaDotNet/AplicativoWeb/Models/ErrorViewModel.cs
namespace AplicativoWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Desktop/EscolaDotNet/AplicativoWeb/Controllers/CursoController.cs
using AplicativoWeb.Models; //camada Model
using Microsoft.AspNetCore.Mvc; //Microsoft
namespace AplicativoWeb.Controllers;//Definindo
//Criamos a classe Controller
public class CursoController:Controller{
     public IActionResult Index(){
        Curso c1 = new Curso();
        //set
        c1.Descricao = "Primeiros Passos no ASP.NET Core";
        c1.TituloInterno = "Desenvolvedor C#";
        c1.TituloMarketing = "Crie Aplicativos Incríveis";        
        //get
        ViewData["curso"] = c1;//passando o objeto       
        return View();
    }
    //Action
    public IActionResult Create(){
        ViewData["titulo"]="Cadastro de Cursos";
        ViewBag.DataHora = DateTime.Now;
        return View();
    }
    
}

Desktop/EscolaDotNet/AplicativoWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AplicativoWeb.Models;

namespace AplicativoWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Desktop/EscolaDotNet/AplicativoWeb/Views/Curso/Create.cshtml
<h1>@ViewData["titulo"]</h1>
<h6>@ViewBag.DataHora</h6>
<!-- Qual a diferença entre
  
  ViewData - Dicionário
  ViewBag
  TempData - Mantem o valor (Sessão)


 -->
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Título Interno</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
</div>
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Título Marketing</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Descrição</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

<button type="button" class="btn btn-outline-dark">Cadastrar</button>

Desktop/EscolaDotNet/AplicativoWeb/Views/Curso/Index.cshtml
@{
  //fortemente tipada
  
    var curso = ViewData["curso"] as Curso;//converter


}
<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
  <div class="card-header"> @curso?.TituloInterno</div>
  <div class="card-body">
    <h5 class="card-title">@curso?.TituloMarketing </h5>
    <p class="card-text"> @curso?.Descricao  </p>
  </div>
</div>

Desktop/EscolaDotNet/AplicativoWeb/Views/Curso/curso.cshtml
<h1>Cadastro de Cursos</h1>

<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>


</textarea>

Desktop/EscolaDotNet/AplicativoWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Desktop/EscolaDotNet/AplicativoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicativoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicativoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplicativoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Create">Novo Curso</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AplicativoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>